_defaults:
  - "configs/models/vitdet_b_vid.yml"
sparsity: 0.79
margin: 0
period: 8
conf: 0.5
# _output: "results/train/vitdet_kitti_vit_baseline_3classes_epochs_8/${_name}/"
_output: "results/train/vitdet_kitti_vit_period_${period}_static_${sparsity}_kr_0.5/${_name}/"
# output_weights: "results/train/vitdet_vid_baseline_lrsched_lr1e-5/vitdet_b_vid_${_name}.pth"
split: "vid_train"
vanilla: false
# weights: "weights/vitdet_b_vid.pth"
weights: "results/train/vitdet_kitti_baseline_3classes_epochs_8/base_672/weights_epoch_6.pth"
# weights: "results/train/vitdet_kitti_vit_baseline_3classes_epochs_8/base_672/weights_epoch_6.pth"
optimizer: "AdamW"
optimizer_kwargs:
  lr: 1.0e-5
  weight_decay: 0.1
lr_scheduler_kwargs:
  min_lr: 1.0e-7
  warmup_epochs: 2
accum_iter: 8
epochs: 8
mask: None
evaluate: False
nb_classes: 4 # 3 + 1 for misc class